# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include ~/.cache/wal/colors-kitty.conf
# END_KITTY_THEME
#

font_family JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14
confirm_os_window_close 0


# Options: fade, slant, separator, powerline, custom, hidden
tab_bar_edge bottom
tab_bar_align left
tab_bar_style powerline
tab_powerline_style round
tab_bar_margin_height 4.0 4.0

# Smooths out the cursor movement
cursor_blink_interval 0.5

#Background
background_opacity 0.85

# Hide the mouse cursor immediately when typing
mouse_hide_wait 3.0

# The color of the window border when multiple windows are open
active_border_color #00ff00

#Trail
cursor_trail 200
